name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        env:
          SUPER_SECRET: ${{ secrets.HIDDEN_URL }}
        run: |
          echo $SUPER_SECRET >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
